version: '3.8'

services:
  backend:
    build:
      context: .
    image: cars
    ports:
      - "3000:3000"
    networks:
      - backend-network

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge