basePath: /api/v1
definitions:
  domain.Car:
    properties:
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/domain.Owner'
      regNum:
        type: string
      year:
        type: integer
    type: object
  domain.CreateCarsRequest:
    properties:
      regNums:
        items:
          type: string
        type: array
    type: object
  domain.Owner:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  domain.UpdateCarRequest:
    properties:
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/domain.Owner'
      regNum:
        type: string
      year:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample server for a car service.
  title: EffectiveMobile Test API
  version: "1.0"
paths:
  /cars:
    get:
      consumes:
      - application/json
      description: Get cars based on query parameters
      parameters:
      - description: Car mark
        in: query
        name: mark
        type: string
      - description: Car model
        in: query
        name: model
        type: string
      - description: Car year
        in: query
        name: year
        type: integer
      - description: Car registration number
        in: query
        name: regNum
        type: string
      - description: Limit for pagination
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Owner's name
        in: query
        name: name
        type: string
      - description: Owner's surname
        in: query
        name: surname
        type: string
      - description: Owner's patronymic
        in: query
        name: patronymic
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Car'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get cars
      tags:
      - cars
    post:
      consumes:
      - application/json
      description: Create new cars with the provided specifications
      parameters:
      - description: Create Cars Request
        in: body
        name: cars
        required: true
        schema:
          $ref: '#/definitions/domain.CreateCarsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Car'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create new cars
      tags:
      - cars
  /cars/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a car by ID
      parameters:
      - description: Car ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a car
      tags:
      - cars
    put:
      consumes:
      - application/json
      description: Update car details by ID
      parameters:
      - description: Car ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Car Request
        in: body
        name: car
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateCarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Car'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a car
      tags:
      - cars
swagger: "2.0"
